### ISSUE TITLE
thanks, costa ui is nice project

### ISSUE THREAD

**Issue by lukolve** [jacobpalm/costa#36]
Hi, i try Costa UI in Dosbox and is run, and its very nice project, only one think is that is so slow i remember when i program in turbo pascal there was ega/vga units and i program graphics too but not so slow. and one improvement maybe you ncan do clock widget. 

my small question where can i obtain a visualbasic package i known only that exist freebasic.

**Comment by jacobpalm** [comment]
Hi lukolve,

Thanks for the feedback. I have been doing a lot of work with the next release to improve speed. The slowest point remains the font function, but icon drawing and other functions have improved drastically since 1.7.0. It runs pretty decent om my 386 clocked at 30 MHz, so it should run pretty well in DOSBox. Maybe try adjusting your CPU cycles?

Visual Basic for DOS is not free software, and isn't sold anymore, so I can't legally link to a copy of it. You will have to find it somewhere yourself, I am afraid.
