### ISSUE TITLE
Some things do not work on virtual box

### ISSUE THREAD

**Issue by fritzmueller** [jacobpalm/costa#44]
I noticed some problems with Costa in virtualbox:
I ran FreeDOS FDT2405 in virtualbox - and inside Costa. The mouse is almost unusable as it sometimes splits into two mouse symbols, especially when moving out of the vbox window.  
The combination ALTL+character to select a choice marked with underscore also does not work.
So it is hard to work with Costa.

Thx.

**Comment by jacobpalm** [comment]
Hi,

I'm not sure I understand the mouse issue completely. The mouse splitting into two mouse cursors sounds like your own Cursor from Windows or whatever OS you are running, is being shown over the Window at the same time as the one in Costa? That might be related to your VirtualBox settings, try configuring VirtualBox to capture the mouse when clicking in the window and see if that works for you.

You don't have to press ALT or CTRL or any other key when using underlined characters as hotkeys - just press the underlined letter and nothing else, and it will activate.

Hope this helps, let me know if not.

**Comment by fritzmueller** [comment]
Hi,

I just installed Costa on a real old machine and there mouse works fine. No need to use ALT or CTRL for using underlined characters is a little new for me, but it works fine on your software.

So I will have to find out what's the problem with virtualbox.

 

Fritz

 
 

Sent: Thursday, May 30, 2024 at 9:25 PM

**Comment by Axle-Ozz-i-sofT** [comment]
[fritzmueller](https://github.com/fritzmueller)
The problem occurs within the drivers in virtualBox. Remember that VitualBox does not officially support DOS.
>
You may notice that your OS mouse is no longer synced in the x.y with the mouse in VirtualBox FreeDOS.
This will happen with most GUI applications in FreeDOS as the window scaling gets messed up. DOS expects a full screen monitor rather than windowed :)
There is very little that you can do other than reset the mouse drivers default scaling an x,y.
>
Usually you can correct it by using the right [Ctrl] to remove the mouse from the VirtualBox window and then re-clicking the OS mouse inside of the window. This resets the VirtualBox screen scaling x,y sync.
>
There are some other mouse tricks that can be done by swapping to the CTMOUSE driver as well, but they are slightly different issues effects :)

**Comment by fritzmueller** [comment]
Thanks for response:

Just to clarify: Costa does not support WIN 3.1 programs?

 

Fritz

 
 

Sent: Sunday, June 02, 2024 at 6:17 AM

**Comment by jacobpalm** [comment]
No, Windows 3.x programs are not supported. That would be a massive undertaking, far too much for the scope of Costa. If you want to run Windows programs, you're probably better off just running Windows. Or running both - Windows for using Windows programs, and Costa for running DOS programs without any potential Windows compatibility issues. That's what I personally do on my DOS computers.
